project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('textadventure/', include('textadventure.urls')),
]

textadventure/urls.py
from django.urls import path

from . import views

urlpatterns = [
        # Default, Station mit dem Namen "start"
        path('', views.station, name="station-default"),
        path('station/<str:name>', views.station, name="station"),
        path('audio', views.audio, name="audio"),
        path('game', views.game, name="game"),
]

textadventure/models.py
from django.db import models

# Create your models here.


class Station(models.Model):
    '''
    Eine Station im Textadventure. Der Name ist eine sprechende ID,
    muss also eindeutig (unique) sein.
    '''
    name = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    bildname = models.CharField(max_length=200, null=True) #mit Pfad angeben
    music = models.TextField(null=True, default="textadventure/soundtrack.mp3")

    def __str__(self):
        return self.name


class Choice(models.Model):
    '''
    Eine Auswahloption. Neben dem Text zur Beschreibung enthält Sie auch den 
    Verweis auf die nächste Station.
    '''
    station = models.ForeignKey(to=Station, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    next_station = models.ForeignKey(to=Station, on_delete=models.CASCADE, related_name="incoming_set")

    def __str__(self):
        return f"{self.text}: {self.next_station.name}" 

textadventure/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.clickjacking import xframe_options_sameorigin

# Create your views here.

from . import models

print("Los geht es hier: http://localhost:8000/textadventure/start")

@xframe_options_sameorigin
def station(request, name="start"):
    '''
    Hier wird die passende Station geholt und ausgegeben.
    Wird kein Name übergeben, dann wird die Station 'start' geholt.
    '''
    station = get_object_or_404(models.Station, name=name) 
    return render(request, "textadventure/station.html", {"station": station})

def game(request, name="game"):
    return render(request, "textadventure/game.html")
    
def audio(request, name="audio"):
    return render(request, "textadventure/audio.html")

textadventure/templates/textadventure/audio.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title></title>
  
</head>
<body>
		{% load static %}
	<audio autoplay loop>
		<source src="{% static 'textadventure/soundtrack.mp3' %}" type="audio/mp3">
		Dein Browser unterstützt die Musikwiedergabe nicht.
	</audio>
</body>
</html>

textadventure/templates/textadventure/game.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Textadventure</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	{% load static %}
	<link href="{% static 'textadventure/images' %}">
  </head>
<frameset cols="200, *" >
	<frame src= {% url 'audio' %}>
	</frame>
	<frame src={% url 'station' 'start'%}>	
	</frame>
</frameset>  

textadventure/templates/textadventure/station.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title></title>  
</head>
<body>
    <div class="container mt-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{station.title}}</h5>
          <p class="card-text">{{station.text |linebreaks}}</p>
		  {% load static %}
		  {% if station.bildname %}
		  	<img src="{% static station.bildname %}" alt="image">
			<br>
		  {% endif %}
			
          {% for choice in station.choice_set.all %}
          <a href="{{choice.next_station.name}}" class="btn btn-outline-secondary">{{choice.text}}</a><br>
          {% endfor %}
        </div>
      </div>
    </div>
</body>
</html>